# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "github-pages", "~> 225", group: :jekyll_plugins
#gem "github-pages", group: :jekyll_plugins
#gem "no-style-please"
#gem "github-pages"
gem "webrick", "~> 1.7"


# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
  gem "jekyll-remote-theme"
end